name: Bug report
description: Create a report to help improve the plugin
labels: [Bug]
body:
- type: markdown
  attributes:
    value: |
      > Before opening a bug report:
      > - Make sure that you're running [the latest version](https://github.com/plan-player-analytics/Plan/releases/latest).
- type: textarea
  attributes:
    label: Describe the issue
    description: A clear and concise description of what the issue is, and when it occurred. Post possible exceptions further down below.
  validations:
      required: true
- type: textarea
  attributes:
    label: Exceptions & other logs
    description: Paste all relevant log files here. Attach files if necessary.
    render: text
- type: textarea
  attributes:
    label: Plugin versions
    description: Write versions of any relevant plugins or software in this section
- type: textarea
  attributes:
    label: Additional information
    description: Any additional information goes here (relevant parts of Plan config, what you attempted, etc).