name: Question
description: Ask a Question about the plugin or installation
labels: [Question]
blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://github.com/plan-player-analytics/Plan/wiki
    about: Please check if the wiki already has answer to your question
  - name: Previous Q&A Discussions
    url: https://github.com/plan-player-analytics/Plan/discussions/new
    about: You can also check if someone else has asked your question already
  - name: New Question to Discussions
    url: https://github.com/plan-player-analytics/Plan/discussions/new
    about: Open a new discussion for your question
