# -----------------------------------------------------
# Plan Bungee Configuration file
# More information about each setting:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Bungee-Configuration
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Bukkit-Configuration
# -----------------------------------------------------
Server:
  IP: 0.0.0.0
Network:
  Name: Plan

Plugin:
  Debug: 'false'
  Locale: default
  Allow-Update-Command: true
  Notify-About-DEV-Releases: false
  KeepLogsForXDays: 7

# -----------------------------------------------------
# More information about SSL Certificate Settings:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/SSL-Certificate-%28HTTPS%29-Set-Up
# -----------------------------------------------------
WebServer:
  Port: 8804
  InternalIP: 0.0.0.0
  Security:
    SSL-Certificate:
      KeyStorePath: 'SSLCertificate.keystore'
      KeyPass: 'default'
      StorePass: 'default'
      Alias: 'alias'
# -----------------------------------------------------
Database:
  MySQL:
    Host: localhost
    Port: 3306
    User: root
    Password: minecraft
    Database: Plan
    # Launch options to append after driver address, for example
    LaunchOptions: "?rewriteBatchedStatements=true&useSSL=false"
# -----------------------------------------------------
Commands:
  AlternativeIP:
    Enabled: false
    Link: your.domain.here:%port%
  Colors:
    Main: '&2'
    Secondary: '&7'
    Highlight: '&f'

Analysis:
  AutoRefreshPeriod: 60
  Active:
    # Minutes a player should play per week to be considered active
    PlaytimeThreshold: 30
    # How many days player should join per week to be considered active
    LoginThreshold: 2
  Export:
    Enabled: false
    DestinationFolder: 'Analysis Results'

Data:
  # How many minutes player has to stay still to be considered AFK
  AFKThresholdMinutes: 3
  Commands:
    LogUnknownCommands: false
    CombineCommandAliases: true
  Geolocations: true
  KeepInactivePlayerDataForDays: 180
# -----------------------------------------------------
Customization:
  UseServerTime: true
  Display:
    SessionsAsTable: false
    LargestWorldPercInSessionTitle: false
    # By Default WorldPie is ordered alphabetically, colors are still determined alphabetically.
    OrderWorldPieByPercentage: false
    MaxSessions: 50
    MaxPlayers: 2500
    MaxPlayersPlayersPage: 25000
    PlayerTableFooter: true
    PlayerIPs: true
    GapsInGraphData: false
  Formatting:
    DecimalPoints: '#.##'
    Dates:
      # RecentDays replaces date with Today, Yesterday, Wednesday etc.
      RecentDays: true
        # Non-regex pattern to replace
        DatePattern: 'MMM d YYYY'
      Full: 'MMM d YYYY, HH:mm:ss'
      NoSeconds: 'MMM d YYYY, HH:mm'
      JustClock: 'HH:mm:ss'
    TimeAmount:
      Year: '1 year, '
      Years: '%years% years, '
      Month: '1 month, '
      Months: '%months% months, '
      Day: '1d '
      Days: '%days%d '
      Hours: '%hours%h '
      Minutes: '%minutes%m '
      Seconds: '%seconds%s'
      Zero: '0s'

# -----------------------------------------------------
# More information about Themes:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Themes
# -----------------------------------------------------
Theme:
  Base: Default
  Font:
    FontStyleSheet: https://fonts.googleapis.com/css?family=Quicksand:300,400
    FontFamily: "'Quicksand', sans-serif"
    Color:
      Dark: Base
      Light: Base
  Colors:
    Main: Base
    Main-Dark: Base
    Secondary: Base
    Secondary-Dark: Base
    Tertiary: Base
    Background: Base
    Table-Light: Base
    Table-Dark: Base
  Graphs:
    PunchCard: Base
    PlayersOnline: Base
    TPS:
      High: Base
      Medium: Base
      Low: Base
    CPU: Base
    RAM: Base
    Chunks: Base
    Entities: Base
    WorldPie: '"#438c99", "#639A67", "#D8EBB5", "#D9BF77", "#0099C6", "#66AA00", "#316395", "#994499", "#22AA99", "#AAAA11", "#6633CC", "#E67300", "#329262", "#5574A6"'
    ActivityPie: '"#228B22", "#A9A9A9", "#808080", "#951800"'
    ServerPreferencePie: '"#0099C6", "#66AA00", "#316395", "#994499", "#22AA99", "#AAAA11", "#6633CC", "#E67300", "#329262", "#5574A6"'

# -----------------------------------------------------
Servers:
  Example:
    WebServerPort: 8034
    ServerName: Example
    ThemeBase: Default